# .streamlit/secrets.toml
[auth]
username = "admin"
password = "admin"

[api]
key = "mjZvXzcQzMalXcRtmzhBT6H2W7Nm068g6WIxisJR"
base_url = "https://naqnlyyxj2.execute-api.eu-west-3.amazonaws.com/prod"
